/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.  By
starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

const ruler2 = () => {
  const fib = [1, 2];
  for (let i = 0; true; i++) {
    const sum = fib[i] + fib[i + 1];
    if (sum < 4000000) {
      fib.push(sum);
    } else {
      return fib.reduce((a, b) => a + (b % 2 === 0 ? b : 0), 0);
    }
  }
};

console.log(ruler2()); // 4613732
